import turtle
wn = turtle.Screen()
zig = turtle.Turtle()
zag = turtle.Turtle()
zig.color("blue")
zag.color("red")
zig.left(180)
zig.forward(120)
zag.forward(120)
zig.right(120)
zag.left(120)
zig.forward(250)
zag.forward(250)
wn.exitonclick()
