import turtle
import math
alex = turtle.Turtle()
wn = turtle.Screen()
dist = math.sqrt(50*50/2)

alex.right(90)
alex.forward(50)
alex.left(90)
alex.forward(50)
alex.left(90)
alex.forward(50)
alex.left(90)
alex.up()
alex.forward(50)
alex.down()
alex.right(135)
alex.forward(dist)
alex.right(90)
alex.forward(dist)
alex.left(45)
alex.forward(60)
alex.right(90)
alex.forward(50)
alex.right(90)
alex.forward(60)
alex.right(180)
alex.forward(60)
alex.left(90)
alex.forward(50)
alex.forward(dist-7)
alex.left(90)
alex.forward(90)


wn.exitonclick()
